version: '3.8'

services:
  app:
    build: .
    container_name: torneo-tenis-app
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mosaikus_mysql
      - DB_DATABASE=torneo_tenis
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - LOG_CHANNEL=stack
      - SESSION_DRIVER=file
      - L5_SWAGGER_GENERATE_ALWAYS=true
    ports:
      - "8080:8080"
    networks:
      - torneo-net
networks:
  torneo-net:
    driver: bridge

volumes:
  db_data:
    driver: local
